Repository newrelic/infra-integrations, pull requests merged in 2018-02, with the labels that each got.

#14 [apache] Add code for creating custom http clients
  integrations/apache/src/status.go
  integrations/apache/src/status_test.go
  vendor/go.datanerd.us/p/meatballs/backend/shared/svccommon/http/client/http_client.go
  vendor/vendor.json
Labels: risk:medium

#15 Release v1.3.0
  CHANGELOG.md
Labels: risk:low

#16 Fix --replaces format for deb packages
  Makefile-package.mk
Labels: risk:high
